# Generated by Django 3.1.1 on 2020-09-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200907_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Comment Author')),
                ('comment_content', models.TextField(max_length=250, verbose_name='Content')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article.article', verbose_name='Article')),
            ],
        ),
    ]
